#! /bin/bash

# Author: Jesse Wood
# Recreates the databases structures for the Benthic Biological Dataset.
# Creates the schema and the table for storing the download information.

DB='nzodn'
SCHEMA='bio_campbell_chatham'
TABLE='bio_campbell_chatham'
USER='nzodn_admin'
FILE='bio_campbell_chatham/ZBD201901-01.zip'
COMMENT='ZBD201901-01: Benthic Biological Campbell Plateau and Chatham Rise (static)'

psql -d $DB -c "drop schema if exists ${SCHEMA} cascade;";

psql -d $DB -c "create schema ${SCHEMA} authorization ${USER};";

psql -d $DB -c "comment on schema ${SCHEMA} is '${COMMENT};'";

psql -d $DB -c "create table ${SCHEMA}.${TABLE} (
                id          serial  primary key,
                filename    text                not null unique,
                url         text                not null unique,
                description text,
                geom        geometry(Polygon)
                );";


psql -d $DB -c "insert into ${SCHEMA}.${TABLE} 
                (filename, url, description, geom)
                values(
                    '${FILE}',
                    'http://www.nzodn.nz/data/${FILE}', 
                    '${COMMENT}',
                    ST_MakeEnvelope(169.1333,-55.6667,188.3967,-41.54167,4326)
                );";

# Grant read access for the nzodn role to query information.
psql -d $DB -c "grant usage on schema ${SCHEMA} to ${DB};"
psql -d $DB -c "grant select on table \"${SCHEMA}\".\"${TABLE}\" to ${DB};"
