#! /bin/bash

# Author: Jesse Wood
# Recreates the databases structures for the Benthic Biological Dataset.
# Creates the schema and the table for storing the download information.

DB='nzodn'
SCHEMA='bio'
TABLE='biological_map'
USER='nzodn_admin'

psql -d $DB -c 'drop schema if exists bio cascade;';

psql -d $DB -c "create schema ${SCHEMA} authorization ${USER};";

psql -d $DB -c "create table ${SCHEMA}.${TABLE} (
                id          serial  primary key,
                filename    text                not null unique,
                url         text                not null unique,
                description text,
                geom        geometry(Polygon)
                );";

psql -d $DB -c "insert into ${SCHEMA}.${TABLE} 
                (filename, url, description,geom)
                values(
                    'bio/bio.zip',
                    'http://www.nzodn.nz/data/bio/bio.zip', 
                    'benthic biological dataset',
                    ST_MakeEnvelope(171.99373,-45.79912,188.39583,-41.53985,4326)
                );";

# Grant read access for the nzodn role to query information.
psql -d $DB -c "grant usage on schema bio to nzodn;"
psql -d $DB -c "grant select on table \"bio\".\"biological_map\" to nzodn;"
